### ISSUE TITLE
Please clarify that OAuth2 is not required

### ISSUE THREAD

**Issue by jech** [wish-wg/webrtc-http-ingest-protocol#16]
Section 4.5 requires the use of a bearer token for authentication, and seemingly excludes the use of HTTP Basic auth.

1. Basic Auth has some advantages over bearer tokens, since Basic has a well-defined structure (e.g. the server knows how to extract the username).  Please recommend support for HTTP Basic.
2. The reference to RFC 6750 implies that OAuth2 is being used.  You usefully clarified this on the maling list:
    ```
    No, at least the idea was not to require oauth/2 for retrieving the bearer
    token, rfc 6750 is just referenced about how to create the request header
    carrying the token. How to generate/gather the bearer token is outside the
    scope of the doc. This how most rest APIs work nowadays.
    ```
    Please put similar language in the draft.

**Comment by theRealWardo** [comment]
I gave this a go. there's an interesting bit here because we're considering mirroring the RTMP approach in so far as the auth is implicit in the URL.

we do `rtmp://live.mux.com/app/{STREAM_KEY}` and are imagining support for WHIP via something akin to `https://whip.mux.com/{STREAM_KEY}`. in such a case, this simple URL by itself contains what we believe to be sufficiently "secret" information to secure ingestion (as we have done this same thing for years in the RTMP world).

**Comment by murillo128** [comment]
clarified in https://github.com/wish-wg/webrtc-http-ingest-protocol/commit/47c7cb5735b99693255cfc295df22abd66069e3b
