### ISSUE TITLE
Explicit HTTP error code

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#164]
Section 4.1.3:

   "If the ICE restart request cannot be satisfied by the WHIP session, the resource MUST return an appropriate HTTP error code"

Elsewhere in the document, the HTTP actual error code to use is specified. Why is only "an appropriate" used for this case?

**Comment by murillo128** [comment]
Because there could be a wide range of reasons why the ice restart could not be completed and we were advised against redefining http error usage in this draft. We were able to introduce http error codes on the error codes because they were well defined and could provide specific extra information to the whip client about the error.
