### ISSUE TITLE
WHIP session definition

### ISSUE THREAD

**Issue by cdh4u** [wish-wg/webrtc-http-ingest-protocol#167]
Section 3:

   *  WHIP session: Indicates the allocated WHIP session by the WHIP
      endpoint for an ongoing ingest session.

This does not define what a WHIP session is, as the definition text contains the terminology it is supposed to define.

**Comment by murillo128** [comment]
how about this?

```
WHIP session: Indicates the allocated HTTP resource by the WHIP
endpoint for an ongoing ingest session.
```

**Comment by cdh4u** [comment]
Your suggested fix would work, assuming that is the only thing we mean by "WHIP session". I.e., "WHIP session" does NOT refer to a session in the traditional meaning of session (SIP session etc). Personally, I would call the allocated resource something else than "session", but if the community has decided to use "session" I will not argue against it.

In the definition of WHIP session URL, I assume you should also change "WHIP resource" to "HTTP resource".

**Comment by murillo128** [comment]
I agree, I used to call it `WHIP resource` instead of `WHIP session` but the httpdir review argued that this would be confusing with `HTTP resource` (as the WHIP endpoint is also an HTTP resource). 

I would prefer avoid calling it `WHIP session resource` but I have not found a better naming for it yet.

**Comment by cdh4u** [comment]
Perhaps we could use "WHIP server endpoint" and "WHIP session endpoint"?
