### ISSUE TITLE
[Juliusz] 4.3 Load balancing

### ISSUE THREAD

**Issue by murillo128** [wish-wg/webrtc-http-ingest-protocol#39]
"WHIP endpoints and media servers may not be colocated..."  I suggest
"might" instead of "may".

"WHIP clients SHALL support HTTP redirection via the 307 Temporary
Redirect response code..."  This is too specific -- clients should obey
any redirect code.

**Comment by adamroach** [comment]
For what it's worth, I think calling out 307 in particular is good, since many (way too many) HTTP clients do not implement 307 or 308 properly, and it's good to call out support for modern redirection codes as a hard prerequisite for WHIP compliance (since 301/302 handling will mess up POST requests, which WHIP relies on).
