### ISSUE TITLE
[CH] Q8: Section 4.2 (Technical)     

### ISSUE THREAD

**Issue by murillo128** [wish-wg/webrtc-http-ingest-protocol#54]
The text says:

   "Unlike [RFC5763] a WHIP client MAY use a setup attribute value of
   setup:active in the SDP offer, in which case the WHIP endpoint MUST
   use a setup attribute value of setup:passive in the SDP answer."

First, check whether it would be useful to also reference RFC 8842.

Second, I think it is a BAD idea to go against the "MUST use setup:actpass" text in RFC 5763. Since you specify that the answerer MUST use setup:passive, there is no reason why the offer couldn't use setup:actpass, following the standard.

**Comment by murillo128** [comment]
The idea is to prevent the WHIP client to have to implement active and passive setup. The MUST for the server is only in case that the client uses the `active` setup attribute, maybe some rewording helps

**Comment by murillo128** [comment]
Yes, we could, but would it be worthy?

If the client sends `active`, server MUST send `passive`.
If the client sends `actpass`, then the client MUST support to receive either an `active` or `passive` response from the server, so I don't think we should put any extra requirement on the server. If the media server wants to only implement `passive` they are allowed in any case.

**Comment by cdh4u** [comment]
> Yes, we could, but would it be worthy?
> 
> If the client sends `active`, server MUST send `passive`. If the client sends `actpass`, then the client MUST
> support to receive either an `active` or `passive` response from the server, so I don't think we should put any extra 
> requirement on the server. If the media server wants to only implement `passive` they are allowed in any case.

The document specifies the behavior of the media server, so even if the standard allows both 'active' and 'passive' you can still specify that a WHIP compliant server MUST send 'passive'. It is better than having the client do something which is not standard compliant.

**Comment by murillo128** [comment]
ok, I get your point.

The idea would be then to ask the client to send `actpass` on the offer, despite only supporting the `active` part, and force the media server to reply `passive`, right?

Not sure if I like it or not, will ping the mailing list for consensus.

**Comment by cdh4u** [comment]
> ok, I get your point.
> 
> The idea would be then to ask the client to send `actpass` on the offer, despite only supporting the `active` part, 
> and force the media server to reply `passive`, right?

Yes. Specify that a WHIP-compliant media server MUST reply 'passive'.

**Comment by lminiero** [comment]
If a MUST has to be added on servers, I think it should be 'active', not passive. It's an unwritten convention in basically all WebRTC applications that who receives the offer will send 'active', and while a convention is not a rule, forcing a change in this pattern would break a lot of implementations out there that may want to support WHIP on the server side.

**Comment by steely-glint** [comment]
Which is exactly why I wanted the original language that the client could say
setup:active to indicate that it _only_ implements DTLS client. Which isn't as unlikely as you might think, especially on devices with a secure element providing the DTLS certificate. 

It makes no sense to have an offer of actpass and then not actually allow both replies.
Either you believe in the O/A model or you don't.   

By the way _all_ my 'server' devices send answers with setup:passive because they are _servers_ so running a DTLS server makes perfect sense. Seems to work fine...

**Comment by cdh4u** [comment]
> Which is exactly why I wanted the original language that the client could say setup:active to indicate
> that it _only_ implements DTLS client. Which isn't as unlikely as you might think, especially on devices
> with a secure element providing the DTLS certificate.
> 
> It makes no sense to have an offer of actpass and then not actually allow both replies. Either you
> believe in the O/A model or you don't.

An implementation can of course send whatever it wants, including setup:active. There is nothing anyone can do about that :)

But I don't think we should standardize such behavior. As far as the WebRTC and SDP O/A standards are concerned, the offerer can act as both DTLS client and server. If that is the wrong assumption, then I think it shall be discussed in the affected WGs, and based on those discussions potentially update RFC 5763, 8839 etc. I don't think a standards document shall discard MUSTs just because we don't want to support required functionality.

> By the way _all_ my 'server' devices send answers with setup:passive because they are _servers_ so running
> a DTLS server makes perfect sense. Seems to work fine...

But then it should not matter if the offer contains setup:actpass, should it? :)

**Comment by murillo128** [comment]
I fully agree with Tim.

WHIP complicane with WebRTC means that WebRTC endpoints (or whatever name we give to them) can act like a WHIP client, but not all WHIP client needs to be fully compliant WebRTC endpoints.

For the server side we are already reducing the requirements of a JSEP client as explained in the gateway draft:

```   WebRTC gateways are intended to communicate with WebRTC
   endpoints[I-D.ietf-rtcweb-overview].  Some features that typical
   WebRTC endpoints are required to support may be meaningless or
   unneccesary for WebRTC gateways; some such things are noted in this
   section.  This lack of conformance means that a gateway is considered
   a WebRTC-compatible endpoint, not a WebRTC endpoint (unless a
   particular gateway claims to be a WebRTC endpoint, which it is of
   course allowed to do).
```

So, I would challenge that reducing the requirements on the WHIP client makes WHIP non-webrtc compliant.

The idea behing this change is that there is no need for a whip client talking to a whip server to have to implement both active and passive setup. Negotiating actpass when only one mode is supported seems completelly wrong to me.

**Comment by lminiero** [comment]
We've already found out that Tim always sends passive from servers, while Janus always sends active when it receives an offer: this means that whatever you force on the WHIP client will break one of the two servers. I think clients should send actpass as the RFC says.

**Comment by murillo128** [comment]
Mandating clients to implement both active and passive is a no go for me. The goal has always been to reduce the burden on the clients because there was none available. Increasing the complexity of implementing them is not going to help.

**Comment by murillo128** [comment]
btw, I think that Tim is referring that his servers respond as passive, while their clients sends active. So his (whip) clients would be able to talk with janus server, which is what we intended.

**Comment by lminiero** [comment]
No, they wouldn't, because Janus expects actpass when it receives an offer, and will set the role of active for itself. Two actives won't get anywhere.

**Comment by cdh4u** [comment]
> Mandating clients to implement both active and passive is a no go for me. The goal has always been to reduce the burden on the clients because there was none available. Increasing the complexity of implementing them is not going to help.

When you say 'clients', what exactly are you referring to? The WebRTC library that you are using in the application?

**Comment by murillo128** [comment]
No, I am referring to the WHIP clients

**Comment by steely-glint** [comment]
Imagine I have a smart camera acting as a WHIP source which can only do Active DTLS (because of a hardware limitation). Let's assume when it tries to talk to Janus it will fail because Janus will only do active.

If the camera signals this in it's WHIP offer with setup:active then the O/A fails early with a sensible error message http status:402
If it sends a (mendacious) setup:actpass  then the connection will silently fail after ice connects and a 16 second DTLS timeout. 

So sending setup:active in the offer is the _right_ thing for the camera to do.
The other option is to say that such hardware shouldn't be doing WHIP, which seems like a needless limitation on hardware encoder design.

**Comment by steely-glint** [comment]
Incidentally I checked my (open source) Whipi client and it actually sends [setup:passive ](https://github.com/pipe/whipi/blob/d0fe6c06f5b34fa832d1ebce0bd228f066920da0/src/main/java/pe/pi/whipi/util/OfferMaker.java#L54)! Which is why it works with Janus.

**Comment by steely-glint** [comment]
Back to the High level point. The WebRTC spec was designed to be Peer-to-Peer - so it makes sense that both sides need equal capabilities since you never know who will initiate an offer - so mandating actpass in the offer is a good idea.

WISH/WHIP is explicitly client-server so asymmetry is to be expected. 

I would argue that the original wording is wrong however - 
"WHIP endpoint MUST
use a setup attribute value of setup:passive in the SDP answer."
Should read 
"WHIP endpoint SHOULD
use a setup attribute value of setup:passive in the SDP answer. Or if it does not support passive it MUST reply with an http 402 error status and an explanation
error message."

**Comment by cdh4u** [comment]
> Back to the High level point. The WebRTC spec was designed to be Peer-to-Peer - so it makes sense that both sides need equal capabilities since you never know who will initiate an offer - so mandating actpass in the offer is a good idea.
> 
> WISH/WHIP is explicitly client-server so asymmetry is to be expected.
> 
> I would argue that the original wording is wrong however - "WHIP endpoint MUST use a setup attribute value of setup:passive in the SDP answer." Should read "WHIP endpoint SHOULD use a setup attribute value of setup:passive in the SDP answer. Or if it does not support passive it MUST reply with an http 402 error status and an explanation error message."

I think it shall be MUST.  If the server cannot do that for whatever reason it will obviously have to return an error. We can for sure specify which error code to use. Also, I think it is better to say that the server MUST follow the procedures in RFC 4573.

Regarding the WHIP client, a compromise would be to say that it SHOULD use actpass, according to 4573, unless it only implements the DTLS client role in which case it can use active. Because, we should not forbid a WHIP client from using the standard 4573 behavior if it is able to do so.

In addition, there could be a note saying a few words about why a WHIP client might only implement the DTLS client role.

**Comment by cdh4u** [comment]
Here is some new text suggestion (I have not created a PR yet) for Section 4.2. Note that I also modify the BUNDLE text.

---

The SDP BUNDLE mechanism [RFC8843] MUST be used by both WHIP clients and media servers. Each m- line MUST be part of a single BUNDLE group.  Hence, when a WHIP client sends an SDP offer, it MUST include a bundle-only attribute in each bundled m- line. In addition, per [8843] the WHIP client and media server will use RTP/RTCP multiplexing for all bundled media. The WHIP client and media server SHOULD include the rtcp-mux-only attribute in each bundled m- line.

When a WHIP client sends an SDP offer, it SHOULD use the setup:actpass attribute, as defined in [RFC5763]. However, if the WHIP client only implements the DTLS client role, it MAY use the setup:active attribute.

NOTE:  [RFC5763] defines that the offerer must use the setup:actpass attribute. However, the WHIP client will always communicate with a media server that is expected to support the DTLS server role, in which case the client might choose to only implement support for the DTLS client role.

---

**Comment by murillo128** [comment]
I like that and I think it is a good compromise, creating the PR now
